### ISSUE TITLE
Action servers, setting up x,y and angle location dynamically

### ISSUE THREAD

**Issue by jonathanleinola** [tthmatt/Omron_LD_ROS_Package#4]
Hey,

How is it possible to set x,y,angle for the robot? I can do it via rviz, but not through code. is it possible to somehow do it and could you help with that?

Greetings,
Jonathan

**Comment by zach-goh** [comment]
Hi Jonathan, may I know what model of robot you are trying to control?  And how/where did you purchase this robot from?

**Comment by jonathanleinola** [comment]
Hey zach! The model is LD90 and i'm doing my master's thesis using this robot (did not purchase it and don't have that information)

**Comment by zach-goh** [comment]
I see.  I wanted to know how you got it to see how old your LD90 is and check for compatibility issues.  May I know which school you are doing your Masters at?  I can try to find out when it was sold.

**Comment by jonathanleinola** [comment]
Hi,

I'm at Aalto university :) Can we continue in private?

-Jonathan


On Feb 1, 2021 11:45, zach-goh <notifications@github.com> wrote:

I see. I wanted to know how you got it to see how old your LD90 is and check for compatibility issues. May I know which school you are doing your Masters at? I can try to find out when it was sold.

**Comment by zach-goh** [comment]
I'm not sure one would how to communicate in private on Github.  But to answer your original question first, the sample script uses uses the goal name and not the x,y,th coordinates to move the robot to it.  Hence you need to create the goals first in Mobile Planner before running a script from ROS.

**Comment by jonathanleinola** [comment]
Ok, no problem. I have already used that script but I would like to have a functionality to dynamically in realtime set different positions in the map (I would get those positions from camera). I’m trying to achieve that by using MoveBaseAction and MoveBaseGoal but have not yet succeeded. Do you think it is doable? I tried also to publish locations to node /goto_point, but it seems that it does not work as i expected. (It wont actually send those directly to the ARCL server

**Comment by zach-goh** [comment]
I haven't used the MoveBaseAction and MoveBaseGoal before so I don't know how they can be used.  But if you know ARCL, you can try to implement this command in ROS: dotask.  The possible tasks can be found on MobilePlanner such as these for driving:
![image](https://user-images.githubusercontent.com/58496505/106563602-fd8edd00-6566-11eb-8883-f5c1dd141802.png)

In ARCL you would then send "dotask move [distance]  [speed] [accel ] [decel] .........." to command the robot to move a certain distance or heading.  This will allow you to move the robot using relative coordinates (relative to where it is currently) - not sure if this method works for your use case.

**Comment by jonathanleinola** [comment]
I'll try that thanks! How about in om_navigation there is the goto_point.cpp, is it possible to write that as a python script so it would take the inputs from camera not grom the rviz gui?

**Comment by jonathanleinola** [comment]
I got it working using the goto_point.cpp file! Also, can i somehow stop the current action?

**Comment by zach-goh** [comment]
I think the goto_point example was not implemented as an action so you can't cancel it.  But you can issue a new ARCL command "stop" if you want to stop the robot.  I don't know if this stops the robot immediately so you have to check if it works for your case.

**Comment by jonathanleinola** [comment]
Ok, thanks. I'll try that. Do you have any example code for the stop command?

On Feb 3, 2021 04:47, zach-goh <notifications@github.com> wrote:

I think the goto_point example was not implemented as an action so you can't cancel it. But you can issue a new ARCL command "stop" if you want to stop the robot. I don't know if this stops the robot immediately so you have to check if it works for your case.

**Comment by jonathanleinola** [comment]
Also if I use those example scripts "goto Goal2" and "goto Goal3", how can I cancel or stop that movement?

**Comment by zach-goh** [comment]
You need to send an ARCL command "stop" to the robot.  It is not implemented in the code but you can reference the way the robot status is obtained by sending the ARCL command "status".  If I am not mistaken, you can call `queue_command()` in `SocketDriver `class.

**Comment by lekoook** [comment]
> 
> 
> Also if I use those example scripts "goto Goal2" and "goto Goal3", how can I cancel or stop that movement?

Hi @jonathanleinola , I was one of the original authors in this package though no longer working on this. As an alternative to @zach-goh 's reply, I believe you can also use ROS actions to achieve (though my memory on this is a little fuzzy, please read this with a grain of salt). You can stop the robot by sending a `stop` ARCL command via ROS action. You can look at the code found in `goto_goal2_action.py` as an example of how to send ARCL command via ROS action. 

If you have familiarised yourself with the ARCL communication, notice that ARCL will return a feedback message whenever you send a ARCL command. This identifying feedback message _along_ with the ARCL command itself, is required to execute the ROS action (which in turn sends the ARCL command). For example, see this [line](https://github.com/zach-goh/Omron_LD_ROS_Package/blob/1410ce8c6b0e7953d371c260ef451dd9aa3a96dc/src/om_aiv_navigation/scripts/goto_goal2_action.py#L17-L18) in `goto_goal2_action.py`. `goto Goal2` is the ARCL command and `Arrived at Goal2` is the expected feedback message. If there are multiple feedback messages expected, you **should** include all of them.

Note: Example code is in Python. If you need to write in C++, you should be able to do it as well since this uses the ROS Action protocol (`actionlib`)

You _should_ (I can't guarantee) be able to execute quite a number of ARCL commands using this ROS Action, though you should test them first, please do it safely. Best of luck!

**Comment by jrajaram20** [comment]
@jonathanleinola 
movebasegoal may not be useful for your case. 
For updating map with new goals you need to stop the robot. Map updates and path planning cannot be active at the same time for LD robots.
Best option is to use goto_point . 
Are you able to test your commands by sending it directly to ARCL server ?

**Comment by jonathanleinola** [comment]
Thanks for the help! I was able to do it via goto_point. I have not tested yet the stop command but will update if i get it working :)
